In [ ]:
import numpy as np

## Numpy array operations

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic slicing :", arr[2:7])
print("with step :", arr[1:8:2])
print("Negative indexing:",arr[-3])

Basic slicing : [3 4 5 6 7]
with step : [2 4 6 8]
Negative indexing: 8


In [4]:
arr = np.arange(1,10)
arr_2d = arr.reshape((3,3))
print(arr_2d)

print("specific element :", arr_2d[1,2])
print("entire row :", arr_2d[1])
print("entire column :", arr_2d[:,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
specific element : 6
entire row : [4 5 6]
entire column : [2 5 8]


## Sorting

In [5]:
unsorted_array = np.array([3,11,4,1,9,2,1,5,6])
print("sorted array :", np.sort(unsorted_array))

arr_2d_unsorted = np.array([[3,1], [1,2], [2,3]])
print("Sorted 2d array by column :\n", np.sort(arr_2d_unsorted, axis=0))
print("Sorted 2d array by rows :\n", np.sort(arr_2d_unsorted, axis=1))

arr_2d_unsorted = np.array([[3,1,5], [8,1,2], [2,7,3]])
print("\nOriginal array\n",arr_2d_unsorted)
print("Sorted 2d array by column :\n", np.sort(arr_2d_unsorted, axis=0))
print("Sorted 2d array by rows :\n", np.sort(arr_2d_unsorted, axis=1))


sorted array : [ 1  1  2  3  4  5  6  9 11]
Sorted 2d array by column :
 [[1 1]
 [2 2]
 [3 3]]
Sorted 2d array by rows :
 [[1 3]
 [1 2]
 [2 3]]

Original array
 [[3 1 5]
 [8 1 2]
 [2 7 3]]
Sorted 2d array by column :
 [[2 1 2]
 [3 1 3]
 [8 7 5]]
Sorted 2d array by rows :
 [[1 3 5]
 [1 2 8]
 [2 3 7]]


## Filters

In [6]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers % 2 == 0]
print("Even numbers :", even_numbers)

Even numbers : [ 2  4  6  8 10]


### filter with mask

In [7]:
mask = numbers > 5 #mask is just a expression that will be evaluated (performed)
print("Number greater than 5 :", numbers[mask])

Number greater than 5 : [ 6  7  8  9 10]


### Fancy indexing vs np.where()

In [8]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP where ", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where  [ 6  7  8  9 10]


In [9]:
condition_arr = np.where(numbers > 5, numbers*4, numbers)
print(condition_arr)

[ 1  2  3  4  5 24 28 32 36 40]


## Adding and Removing data

In [10]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

add = arr1 + arr2
print(add)

combined = np.concatenate((arr1, arr2))
print(combined)

[5 7 9]
[1 2 3 4 5 6]


### Array Compatibility

In [13]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9,2])

print("Compatibility shapes :", a.shape == b.shape)
print("Compatibility shapes :", a.shape == c.shape)

Compatibility shapes : True
Compatibility shapes : False


In [18]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original, new_row))
print(original)
print("\n",with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original, new_col))
print("\nWith column\n", with_new_col)

[[1 2]
 [3 4]]

 [[1 2]
 [3 4]
 [5 6]]

With column
 [[1 2 7]
 [3 4 8]]


In [19]:
arr = np.array([1,2,3,4,5,6])
deleted = np.delete(arr, 3)
print("Array after deletion:", deleted)

Array after deletion: [1 2 3 5 6]
