# Numpy array and basics


In [18]:
import numpy as np

### creating array from list

In [19]:
arr_1d = np.array([1,2,3,4,5])

arr_2d = np.array([[1,2,3],[4,5,6]])

In [20]:
print(arr_1d)
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


### list vs numpy array

In [21]:
py_list = [1,2,3,4]
print("python list multiplication : ", py_list*2)

np_arr = np.array([1,2,3,4])
print("python array multiplication : ", np_arr*2)

import time
start = time.time()

py_list = [i*2 for i in range(1000000)]
print("\n List operation time : ", time.time() - start)


start = time.time()
np_arr = np.arange(1000000)*2
print("\n Numpy operation time : ", time.time() - start)

python list multiplication :  [1, 2, 3, 4, 1, 2, 3, 4]
python array multiplication :  [2 4 6 8]

 List operation time :  0.11565804481506348

 Numpy operation time :  0.008629560470581055


### creating various numpy arrays from sratch 

In [35]:
zeros = np.zeros((3,4))
print("\nzero array : \n", zeros)

ones = np.ones((4,2))
print("\nones array : \n", ones)

full = np.full((3,3), 5)
print("\n full array : \n", full)



random = np.random.random((3,5))
print("\n random array : \n", random)

sequence = np.arange(0,10,2)
print("\n sequence array : ", sequence)


zero array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

ones array : 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

 full array : 
 [[5 5 5]
 [5 5 5]
 [5 5 5]]
2

 random array : 
 [[0.3628606  0.03388959 0.48952591 0.11394784 0.09051028]
 [0.82500843 0.52664251 0.86284791 0.42352479 0.47581261]
 [0.15426562 0.90742073 0.70363407 0.72601314 0.67804786]]

 sequence array :  [0 2 4 6 8]


## Vector, Matrix, Tensor

In [44]:
vector = np.array([1,2,3,4]) #a simple array
print("Vector :", vector)
matrix = np.array([
                    [2,3,4,4],
                    [6,7,8,9],
                    [0,9,8,7]    
                ])
print("matrix : \n", matrix)
print("dimension of the matrix:",matrix.ndim)

tensor = np.array([[[1,2], [3,4]],
                  [[5,6], [7,8]]])
print(tensor)
print(tensor.ndim)

Vector : [1 2 3 4]
matrix : 
 [[2 3 4 4]
 [6 7 8 9]
 [0 9 8 7]]
dimension of the matrix: 2
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3


### Array properties

In [48]:
arr = np.array([[1,2,3,4],
               [5,6,7,8]])
print("Shape :", arr.shape)
print("Dimension :", arr.ndim)
print("Size :", arr.size)

Shape : (2, 4)
Dimension : 2
Size : 8


In [58]:
arr = np.arange(12)
print("\nOriginal Array :", arr)

reshaped = arr.reshape((3,4))
print("\nReshaed array :", reshaped)

flattened = reshaped.flatten()
print("\nFlattened array :", flattened)

# ravel returns a view instead of copy
raveled = reshaped.ravel()
print("\n Raveled array :", raveled)

transpose = reshaped.T
print("Tranpose array :\n", transpose)


Original Array : [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaed array : [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened array : [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled array : [ 0  1  2  3  4  5  6  7  8  9 10 11]
Tranpose array :
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
