In [2]:
a = 13
a

13

# Welcome
* 1
* 2
* 3
  hello **everyone**



In [1]:
import numpy as np

In [9]:
a1 = np.array([])


In [6]:
a2 = np.array([1,2,3,4, "hello", 23.45, True])
a2

array(['1', '2', '3', '4', 'hello', '23.45', 'True'], dtype='<U32')

In [7]:
a2.itemsize

128

In [10]:
a3 = np.array([1,2,3,4, 45 + 43j, "hello"])
a3

array(['1', '2', '3', '4', '(45+43j)', 'hello'], dtype='<U64')

In [11]:
a3.itemsize

256

In [13]:
a1 = np.arange(24)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [15]:
ar1 = np.ones(3)
ar1

array([1., 1., 1.])

In [17]:
arr2 = np.zeros(4)
arr2

array([0., 0., 0., 0.])

In [18]:
arr2 = np.ones([3,4], dtype=int)
arr2

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### By default np.ones, .zeros, .identity creates a float array

In [20]:
arr3 = np.identity(3,dtype=int)
arr3

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [21]:
arr4 = np.random.randint(23, 45, 6)
arr4

array([30, 42, 44, 32, 30, 34], dtype=int32)

In [22]:
arr5 = np.random.normal(0.0, 1.1, 8)
arr5

array([ 1.49624236, -0.30492165,  0.99639701, -0.4286189 , -1.19234824,
        2.52019816,  0.14305253,  1.55970989])

In [ ]:
import numpy as np

In [2]:
import numpy as np
a1 = np.array([1,2,3,4,5,6])
a1

array([1, 2, 3, 4, 5, 6])

a1

In [ ]:
a1

In [3]:
a1[-1]

np.int64(6)

In [4]:
a1[2:]

array([3, 4, 5, 6])

In [9]:
arr6 = np.arange(24).reshape(6,4)
arr6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [12]:
arr6[1:3,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [13]:
arr6[2:, :-1] 

array([[ 8,  9, 10],
       [12, 13, 14],
       [16, 17, 18],
       [20, 21, 22]])

In [16]:
arr6[:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [33]:
arr6[1:,1:-1] #arr[row, col]

array([[ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [ ]:
# To reverse rows

arr6[::-1]

array([[20, 21, 22, 23],
       [16, 17, 18, 19],
       [12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [31]:
#to reverse cols

arr6[::, ::-1]

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8],
       [15, 14, 13, 12],
       [19, 18, 17, 16],
       [23, 22, 21, 20]])

In [32]:
# to reverse cols and rows both

arr6[::-1,::-1]

array([[23, 22, 21, 20],
       [19, 18, 17, 16],
       [15, 14, 13, 12],
       [11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

In [34]:
arr6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [35]:
arr6[::2]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [37]:
arr6[::2,::3]

array([[ 0,  3],
       [ 8, 11],
       [16, 19]])

In [38]:
arr7 = np.array([1,2,3,4,5])
arr8 = np.array([11,12,13,14,15])

In [39]:
np.hstack([arr7,arr8])

array([ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15])

In [ ]:
np.vstack([arr7,arr8]) # same as np.stack([])

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [42]:
arr9 = np.arange(10)
arr9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.split(arr9, 2)  # arr9 has 10 ele so the we split the array in it's factors i.e 1,2,5,10

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [ ]:
np.split(arr9,5) # 5 arrays of 2 eles

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [ ]:
np.linspace(120, 200, 5) #use to generate array of evenly spaced numbers over a fixed interval

array([120., 140., 160., 180., 200.])

In [51]:
np.linspace(125,138, 9)

array([125.   , 126.625, 128.25 , 129.875, 131.5  , 133.125, 134.75 ,
       136.375, 138.   ])

In [52]:
np.linspace(12,24)

array([12.        , 12.24489796, 12.48979592, 12.73469388, 12.97959184,
       13.2244898 , 13.46938776, 13.71428571, 13.95918367, 14.20408163,
       14.44897959, 14.69387755, 14.93877551, 15.18367347, 15.42857143,
       15.67346939, 15.91836735, 16.16326531, 16.40816327, 16.65306122,
       16.89795918, 17.14285714, 17.3877551 , 17.63265306, 17.87755102,
       18.12244898, 18.36734694, 18.6122449 , 18.85714286, 19.10204082,
       19.34693878, 19.59183673, 19.83673469, 20.08163265, 20.32653061,
       20.57142857, 20.81632653, 21.06122449, 21.30612245, 21.55102041,
       21.79591837, 22.04081633, 22.28571429, 22.53061224, 22.7755102 ,
       23.02040816, 23.26530612, 23.51020408, 23.75510204, 24.        ])